# Autograd with tensors

In [32]:
import torch

In [35]:
w = torch.randn(4,3, requires_grad=True)
w

tensor([[ 0.1919,  1.2638, -1.2904],
        [-0.7911, -0.0209, -0.7185],
        [ 0.5186, -1.3125,  0.1920],
        [ 0.5428, -2.2188,  0.2590]], requires_grad=True)

In [36]:
w.requires_grad_(False) #The _ is for in place operations. It's quite conventionally used all over pytorch
w

tensor([[ 0.1919,  1.2638, -1.2904],
        [-0.7911, -0.0209, -0.7185],
        [ 0.5186, -1.3125,  0.1920],
        [ 0.5428, -2.2188,  0.2590]])

In [37]:
w.requires_grad_(True)
w

tensor([[ 0.1919,  1.2638, -1.2904],
        [-0.7911, -0.0209, -0.7185],
        [ 0.5186, -1.3125,  0.1920],
        [ 0.5428, -2.2188,  0.2590]], requires_grad=True)

In [38]:
y = torch.exp(w)

''' Notice that pytorch keeps track of the gradient operation. In this case, since the tensor is programmed as differentiable, pytorch
stick a gradient function with it. In this case, it's the exponential backward function.
'''
y 



tensor([[1.2115, 3.5388, 0.2752],
        [0.4533, 0.9793, 0.4875],
        [1.6797, 0.2691, 1.2117],
        [1.7208, 0.1087, 1.2956]], grad_fn=<ExpBackward0>)

In [ ]:
#Try computing the y.backward(). The backward function works only on scalar. There is one additional requirement to make it work on vectors:
# Check this link: https://abishekbashyall.medium.com/playing-with-backward-method-in-pytorch-bd34b58745a0

In [40]:
print(y.grad_fn)

In [41]:
#Let's do the same with a scalar
output = y.mean()
output

tensor(1.1026, grad_fn=<MeanBackward0>)

In [42]:
#Let's get the gradients of w
print(w.grad)

None


In [43]:
#With the backward function, the gradients are calculated
output.backward()

In [44]:
#Notice that we did not get None when printing the gradients of w. We rather got number which are the gradients of w
print(w.grad)

# From w, we compute the exponentials, which gives y. Then, we have an average over the exp, which gives output.

tensor([[0.1010, 0.2949, 0.0229],
        [0.0378, 0.0816, 0.0406],
        [0.1400, 0.0224, 0.1010],
        [0.1434, 0.0091, 0.1080]])


In [45]:
print(output.requires_grad)

True


In [46]:
with torch.no_grad():
    output = (w + y).mean()
print(output.requires_grad)

False
